### PR TITLE
Create .npmignore

### PR DESCRIPTION
**Pull request by pkuczynski**

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
`npm explore foo && npm install && npm test` should always work.

Either way, an `.npmignore` file should start by duplicating `.gitignore`, and then adding whatever entries are desired. eslint and nyc configs are *required* to be published.

**Comment by ljharb** [comment]
I've gone ahead and updated this to exclude the only thing that can really be excluded, the github actions workflows.

**Comment by pkuczynski** [comment]
I am just wondering: why would you like to publish `eslint` or `istanbul` configuration? This does not make sense in the published npm package. Make only sense in development...

**Comment by ljharb** [comment]
Because I need to be able to run the tests for each of my installed dependencies, even when I have no internet access. eslint and istanbul are part of `npm test`, so those must be included.

**Comment by pkuczynski** [comment]
In a development mode sure, but in a published package? I hardly ever see any package publishing tests, and as a user, I would like to see the smallest package, so install works fastest... That was my idea behind updating .npmignore...

**Comment by ljharb** [comment]
Every published package is used in development. I'm saying when I develop my app, which depends on this package, I want to be able to run this package's tests without having to track down the git repo.

The majority of packages do, in fact, publish tests, as do all of my packages (which alone constitute over 10% of npm's traffic).

**Comment by pkuczynski** [comment]
I run a very quick check on my example node.js project (ts-based). Out of 724 packages only 70 do publish tests. Of course, there is no quick way to determine if the source code does contain any tests for them, yet this is far from being majority...

So how did you checked that majority of npm packages publish tests?

**Comment by ljharb** [comment]
That's too small a sample size to give you reliable results; but you're right, my claim is also not based on a reliable means of metrics-gathering. At the very least, sufficient packages publish tests that it's a normal thing to do, and all of my packages will continue to do it.

**Comment by ljharb** [comment]
(Your additional commits don't fix things; the entries in gitignore must remain there as well)

**Comment by pkuczynski** [comment]
Yeah, that's what I expected regarding the reliability of your claim :) At least I tried to get some kind of measurable metric ;)

One way or another, it's your package and you might or might not agree with me :)

**Pull request closed without merging**
